### ISSUE TITLE
Starship disabled due to TERM=dumb

### ISSUE THREAD

**Issue by spencer-allen-baker-hughes** [emacs-eaf/eaf-terminal#16]
In NTEmacs my prompt displays 
Starship disabled due to TERM=dumb >

Expected 
C:\Windows\System32                                                                                          16:52:08
❯

**Comment by manateelazycat** [comment]
I don't use Windows, can't help you, sorry.

**Comment by ntemacsguy** [comment]
Can confirm Starship prompt works as expected on Linux.

echo $TERM
xterm-color

**Comment by shentonfreude** [comment]
On Linux, fire up emacs, do: 
```M-x shell```
In the shell, enter
```echo $TERM```

See that it shows "dumb". It's an Emacs-ism, not a Windows-ism.

**Comment by manateelazycat** [comment]
https://github.com/mumu-lhl/eaf-pyqterminal

is better eaf termianl
